on: workflow_dispatch
env:
  FILE_TEMP_NAME: __4rPMDBdWUnHr__
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Hello, World!" >  ${{env.FILE_TEMP_NAME}}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.FILE_TEMP_NAME}}
          path: ${{env.FILE_TEMP_NAME}}

  push-kara:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          ref: kara

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{env.FILE_TEMP_NAME}}

      - run: |
          mv ${{env.FILE_TEMP_NAME}} hello.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add hello.txt
          git commit -m "Bot added hello.txt"
          git push
